#!/bin/bash 
clear
echo -e "\e[1;32m          .--.\e[0m"
echo -e "\e[1;32m::\\\`--._,'.::.\`._.--'/::::\e[0m"
echo -e "\e[1;32m::::.  \` __::__ '  .::::::\e[0m"
echo -e "\e[1;32m::::::-:.\`'..\`'.:-::::::::\e[0m"
echo -e "\e[1;32m::::::::\\ \`--' /::::::::::\e[0m"
echo ""
echo -e "\e[1;34m\"$(shuf -n 1 /usr/bin/yoda.quotes)\"\e[0m"

